name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u  ${{secrets.DOCKER_USERNAME}} -P ${{secrets.DOCKER_PASSWORD}}
      - run: docker -build -t khalid/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true khalid/react-test npm test
